define([
    './AccordionMenuCtrl',
    './PersonalnyjAkkaunt',
    './Rezoljucii',
    './PersonalnyeDokumenty',
    './Kalendar',
    './Soobshhenija',
    './Organajzer',
    './Fotografii',
    './Novosti',
    './Groups',
    './ModulSozdanijaDokumentov',
    './KorporativnyjAkkaunt',
    './Filialy',
    './Otdely',
    './KorporativnyeDokumenty',
], function () {});